--enable-parallel-downloading 
--ignore-gpu-blocklist 
--enable-zero-copy 
--enable-gpu-rasterization 
--ozone-platform=wayland 
--wayland-text-input-version=3 
--enable-wayland-ime 
--gtk-version=4 
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo,TouchpadOverscrollHistoryNavigation,PlatformHEVCDecoderSupport,WaylandSessionManagement,WaylandTextInputV3,WaylandUiScale,WaylandWindowDecorations,FFmpegSoftwareHEVC,FocusMode,OverlayScrollbar,TreesInViz
